"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

exports.__esModule = true;
exports.default = exports.version = exports.install = void 0;

var _icon = _interopRequireDefault(require("./icon"));

exports.minIcon = _icon.default;
// This file is auto generated by build/build-entry.js
var version = '0.0.2';
exports.version = version;
var components = [_icon.default];

var install = function install(Vue) {
  if (install.installed) return;
  Object.keys(components).forEach(function (key) {
    console.log('key', key);
    Vue.component(key, components[key]);
  });
};
/* istanbul ignore if */


exports.install = install;

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

var _default = {
  install: install,
  version: version
};
exports.default = _default;