// This file is auto generated by build/build-entry.js
import Icon from './icon';
var version = '0.0.1';
var components = [Icon];

var install = function install(Vue) {
  components.forEach(function (Component) {
    Vue.use(Component);
  });
};
/* istanbul ignore if */


if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export { install, version, Icon };
export default {
  install: install,
  version: version
};