// This file is auto generated by build/build-entry.js
import minIcon from './icon';
var version = '0.0.3';
var components = {
  minIcon: minIcon
};

var install = function install(Vue) {
  console.log('com', components);
  Object.keys(components).forEach(function (key) {
    console.log('key', key);
    Vue.component(key, components[key]);
  });
};
/* istanbul ignore if */


if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export { install, version, minIcon };
export default {
  install: install,
  version: version
};