// This file is auto generated by build/build-entry.js
import { VueConstructor } from 'vue/types';
import minIcon from './icon';

declare global {
  interface Window {
    Vue?: VueConstructor;
  }
}

const version = '0.0.2';
const components: any = [
  minIcon
];

const install = (Vue: VueConstructor) => {
  if (install.installed) return
  Object.keys(components).forEach(key => {
    console.log('key', key)
    Vue.component(key, components[key])
  })
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  minIcon
};

export default {
  install,
  version
};
